[id="Composite_Content_Views_Overview_{context}"]
= Composite Content Views Overview

A composite content view combines the content from several Content Views.
For example, you might have separate Content Views to manage an operating system and an application individually.
You can use a composite content view to merge the contents of both Content Views into a new repository.
The repositories for the original Content Views still exist but a new repository also exists for the combined content.

If you want to develop an application that supports different database servers.
The _example_application_ appears as:

|===
| _example_software_

| Application
| Database
| Operating System
|===

Example of four separate Content Views:

* {RHEL} (Operating System)
* PostgreSQL (Database)
* MariaDB (Database)
* _example_software_ (Application)

From the previous Content Views, you can create two composite content views.

Example composite content view for a PostgreSQL database:

|===
| Composite Content View 1 {endash} _example_software_ on PostgreSQL

| _example_software_ (Application)
| PostgreSQL (Database)
| {RHEL} (Operating System)
|===

Example composite content view for a MariaDB:

|===
| Composite Content View 2 {endash} _example_software_ on MariaDB

| _example_software_ (Application)
| MariaDB (Database)
| {RHEL} (Operating System)
|===

Each Content View is then managed and published separately.
When you create a version of the application, you publish a new version of the composite content views.
You can also select the *Auto Publish* option when creating a composite content view, and then the composite content view is automatically republished when a Content View it includes is republished.

.Repository restrictions
Docker repositories cannot be included more than once in a composite content view.
For example, if you attempt to include two Content Views using the same docker repository in a composite content view, {ProjectServer} reports an error.
